homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Viebrantz
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation  
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Cuiaba  
  customize: !include customize.yaml

# Activate cloud
cloud:

# Homekit config
homekit:
   
# Show config menu
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enable ios app
# ios: 

# Track the sun
# sun:

# Enables the frontend
frontend:

# Enable http
http:
#  api_password: !secret api_password

# Enable Hue Bridge
#emulated_hue:
#  host_ip: !secret home_central_ip
#  listen_port: 80

mqtt:
  #broker: !secret mqtt_broker_host
  #port: !secret mqtt_broker_port
  #client_id: home-assistant-100
  #keepalive: 120
  discovery: True
  embedded:
    listeners:
      default:
        max-connections: 5000
        type: tcp
      my-tcp-1:
        bind: 0.0.0.0:1883
      ws-1:
        bind: 0.0.0.0:9090
        type: ws
    auth:
      plugins: ['auth.anonymous']
      allow-anonymous: true
  broker: 127.0.0.1
  port: 1883

sensor: !include_dir_list sensors/
binary_sensor: !include_dir_list binary_sensors/
#mysensors: !include mysensors.yaml
switch: !include_dir_list switches/
light: !include_dir_list lights/
#camera: !include_dir_list cameras/
group: !include groups.yaml
#device_tracker: !include_dir_list device_trackers/
automation: !include_dir_list automations/
#script: !include_dir_merged_named scripts/

logger:
  default: info

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:
