alias: Desliga sensor porta
trigger:
  platform: state
  entity_id: binary_sensor.sensor_porta
  to: 'on'
action:
  - delay:
      seconds: 10
  - service: mqtt.publish
    data:
      topic: "rfbridge/value/166860533"
      payload: "OFF"
      retain: true