alias: Desliga sensor presenca
trigger:
  platform: state
  entity_id: binary_sensor.sensor_presenca
  to: 'on'
action:
  - delay:
      seconds: 10
  - service: mqtt.publish
    data:
      topic: "rfbridge/value/184462069"
      payload: "OFF"
      retain: true